multimodal_imitation_objective:
  _target_: nuplan.planning.training.modeling.objectives.multimodal_imitation_objective.MultimodalImitationObjective
  _convert_: 'all'

  weight: 1.0                  # weight contribution to the overall loss
