_target_: nuplan.planning.training.modeling.models.diffusion_model_ma.DiffusionModelMA
_convert_: 'all'

# Model setup
feature_dim: 128

# Diffusion parameters
T: 64
sigma_data: 1.0
sigma_min: 2e-3
sigma_max: 8e1
rho: 7
p_mean: -1.2
p_std: 1.2

use_pca: True
k: 10
pca_params_path: /zfsauton2/home/brianyan/nuplan-devkit/pca_params.th
params_path: /zfsauton2/home/brianyan/nuplan-devkit/params.th

# VectorMapFeatureBuilder
vector_map_feature_radius: 50    # [m] The query radius scope relative to the current ego-pose.
vector_map_connection_scales: [1, 2, 3, 4] # Use 4 scale connections which consider 1,2,3,4-hop neighbor lane

# Parameters for past trajectory
past_trajectory_sampling:
  _target_: nuplan.planning.simulation.trajectory.trajectory_sampling.TrajectorySampling
  _convert_: 'all'
  num_poses: 4      # target future poses
  time_horizon: 1.5  # [s] time horizon of future poses

# Parameters for predicted trajectory
future_trajectory_sampling:
  _target_: nuplan.planning.simulation.trajectory.trajectory_sampling.TrajectorySampling
  _convert_: 'all'
  num_poses: 16      # target future poses
  time_horizon: 8.0  # [s] time horizon of future poses
